from collections import namedtuple

Model = namedtuple( 'Model', 'name description params icon' )
Param = namedtuple( 'Param', 'name type size isNull isEmpty default relationship relationship_model' )

CREATION_PATH = "/Users/codethefuckout/Documents"
DJANGO_MODEL_PARAMS_ROUTE = "resources/django/django_model_params.json"
DJANGO_URL_IMPORTS_ROUTE = "resources/django/django_url_imports.txt"
DJANGO_MODEL_IMPORTS_ROUTE = "resources/django/django_model_imports.txt"
DJANGO_SERIALIZER_IMPORTS_ROUTE = "resources/django/django_serializer_imports.txt"
DJANGO_APIVIEW_IMPORTS_ROUTE = "resources/django/django_apiview_imports.txt"

MODEL_STRUCT_FILE = "resources/django/model_struct.txt"
SERIALIZER_STRUCT_FILE = "resources/django/serializer_struct.txt"
API_VIEW_STRUCT_FILE = "resources/django/apiview_struct.txt"

CONTROLLER_STRUCT_FILE = "resources/angularjs/repository_controllerjs_struct.txt"
ROUTE_STRUCT_FILE = "resources/angularjs/routejs_struct.txt"
ANGULARJS_MODEL_PARAMS_ROUTE = "resources/angularjs/angularjs_model_params.json"

PARAM_FORMAT = "\t{0}\n"
DEFAULT_FORMAT_STR = "default = '{0}'"
DEFAULT_FORMAT_NUM = "default = {0}"
P_CONFIG = "P_CONFIG"
P_NAME = "P_NAME"
bignumber_t = "bignumber"
number_t = "number"
text_t = "text"
date_t = "date"
decimal_t = "decimal"
datetime_t = "datetime"
bool_t = "bool"
MTM = "MTM"
FK = "FK"
MODEL = "MODEL"
DESCRIPTION = "DESCRIPTION"
PARAMS = "PARAMS"
M_NAME = "M_NAME"
FK_MODEL = "FK_MODEL"
MTM_MODEL = "MTM_MODEL"
apiview = "apiview"
urls = "urls"
url_list = "url_list"
url_create = "url_create"
url_list_create = "url_list_create"
url_update_retrieve_delete = "url_update_retrieve_delete"
controller_parse = "controller_parse"

version1_8 = "v1.8"
version1_5_2 = "v1.5.2"
FIELDS = "FIELDS"
RELATIONSHIPS = "RELATIONSHIPS"
MTM_PARAMS = "MTM_PARAMS"
CREATE_PARAMS = "CREATE_PARAMS"
UPDATE_PARAMS = "UPDATE_PARAMS"
URLPATTERNS_CONTENT = "URLPATTERNS_CONTENT"
M_MODEL = "M_MODEL"
MAYSMODEL = "MAYSMODEL"
NUMBER_PARAMS = "NUMBER_PARAMS"

format_t = "format"
false = "false"
true = "true"
